apiVersion: v1
kind: Service
metadata:
  name: myapp-backend
  namespace: prod
spec:
  selector:
    app: myapp-backend
  ports:
    - port: 5000
      targetPort: 5000
  #type: ClusterIP
  type: LoadBalancer