name: CI/CD Pipeline

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: buddywise.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t buddywise.azurecr.io/todo-backend:latest -f Dockerfile.backend .
          docker push buddywise.azurecr.io/todo-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t buddywise.azurecr.io/todo-frontend:latest -f Dockerfile.frontend .
          docker push buddywise.azurecr.io/todo-frontend:latest
