name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t myapp-backend:latest ./backend
          docker build -f frontend/todo/Dockerfile -t my-frontend-app ./frontend/todo
          docker tag myapp-backend:latest mydockerhub/myapp-backend:latest
          docker tag myapp-frontend:latest mydockerhub/myapp-frontend:latest

      - name: Push Docker images    
        run: |
          docker login -u yadagirihari -p N@nnaH@ri81189
          docker push mydockerhub/myapp-backend:latest
          docker push mydockerhub/myapp-frontend:latest
